# Generated by Django 4.2.9 on 2024-05-05 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="summary",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
