# Generated by Django 4.2.9 on 2024-05-05 15:33

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0002_service_summary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name="Content"),
        ),
    ]
