# Generated by Django 4.2.9 on 2024-05-05 17:16

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0003_alter_product_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name="Content"),
        ),
    ]
